package com.aos.productsapi.mapper;

import org.springframework.stereotype.Component;

import com.aos.productsapi.dto.ProductDTO;
import com.aos.productsapi.model.Product;

/**
 * Utility interface for converting between {@link Product} entities and {@link ProductDTO} objects.
 */
@Component
public interface ProductMapper {

    /**
     * Converts a Product entity to a ProductDTO.
     *
     * @param product the Product entity to convert
     * @return a ProductDTO containing the entity's data
     */
    static ProductDTO toDTO(Product product) {
        return new ProductDTO(
                product.getId(),
                product.getName(),
                product.getDescription(),
                product.getValue(),
                product.getQuantity()
        );
    }

    /**
     * Converts a ProductDTO to a Product entity.
     * The returned entity has no ID set, as it is intended for creation (ID is generated by the DB).
     *
     * @param productDTO the ProductDTO to convert
     * @return a Product entity containing the DTO's data
     */
    static Product toEntity(ProductDTO productDTO) {
        return new Product(
                productDTO.getName(),
                productDTO.getDescription(),
                productDTO.getValue(),
                productDTO.getQuantity()
        );
    }
}
